FS-SAM2:
  framework: FS-SAM2
  model_architecture: FS-SAM2
  model_name: FS-SAM2
  method: FewShotLearning
  train_params:
    - name_en: model
      name_cn: 模型
      part_index: 0
      params:
        - name_en: sam2_checkpoint
          name_cn: SAM2 权重
          value: python/fornib/FS-SAM2/checkpoint/sam2.1_hiera_base_plus.pt
          value_type: string
          control_type: file

        - name_en: sam2_cfg
          name_cn: SAM2 配置
          value: ""
          value_type: string
          control_type: file

    - name_en: training
      name_cn: 训练参数
      part_index: 0
      params:
        - name_en: kshot
          name_cn: K-shot
          value: 1
          value_type: int
          value_range: [1, 16, 1]
          control_type: spin

        - name_en: epochs
          name_cn: 训练轮数
          value: 50
          value_type: int
          value_range: [1, 10000, 1]
          control_type: spin

        - name_en: batch_size
          name_cn: Batch Size
          value: 2
          value_type: int
          value_range: [1, 128, 1]
          control_type: spin

        - name_en: num_workers
          name_cn: 数据线程数
          value: 0
          value_type: int
          value_range: [0, 128, 1]
          control_type: spin

        - name_en: learning_rate
          name_cn: 学习率
          value: 0.0001
          value_type: double
          value_range: [0.000001, 0.01, 0.000001]
          control_type: spin

        - name_en: weight_decay
          name_cn: Weight Decay
          value: 0.000001
          value_type: double
          value_range: [0.0, 0.01, 0.000001]
          control_type: spin

    - name_en: network
      name_cn: 网络参数
      part_index: 1
      params:
        - name_en: image_size
          name_cn: 图像尺寸
          value: 1024
          value_type: int
          value_range: [64, 8192, 64]
          control_type: spin

  test_params:
    - name_en: model
      name_cn: 模型
      part_index: 0
      params:
        - name_en: sam2_checkpoint
          name_cn: SAM2 权重
          value: python/fornib/FS-SAM2/checkpoint/sam2.1_hiera_base_plus.pt
          value_type: string
          control_type: file

        - name_en: sam2_cfg
          name_cn: SAM2 配置
          value: ""
          value_type: string
          control_type: file

    - name_en: inference
      name_cn: 推理参数
      part_index: 0
      params:
        - name_en: checkpoint_path
          name_cn: 检查点路径
          value: ""
          value_type: string
          control_type: file

        - name_en: output_dir
          name_cn: 输出目录
          value: ""
          value_type: string
          control_type: path

        - name_en: kshot
          name_cn: K-shot
          value: 1
          value_type: int
          value_range: [1, 16, 1]
          control_type: spin

        - name_en: image_size
          name_cn: 图像尺寸
          value: 1024
          value_type: int
          value_range: [64, 8192, 64]
          control_type: spin
