#pragma once

// generated by 3rdparty/sqlpp11/scripts/sqlite2cpp.py src/database/include/database/ddl/create_feature_search_settings.sql src/database/include/database/ddl/FeatureSearchSettingsTable dltool::database

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace dltool
{
namespace database
{
  namespace FeatureSearchSettings_
  {
    struct Id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct Key
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "key";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T key;
            T& operator()() { return key; }
            const T& operator()() const { return key; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct Value
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "value";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T value;
            T& operator()() { return value; }
            const T& operator()() const { return value; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct Mtime
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "mtime";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T mtime;
            T& operator()() { return mtime; }
            const T& operator()() const { return mtime; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
  } // namespace FeatureSearchSettings_

  struct FeatureSearchSettings: sqlpp::table_t<FeatureSearchSettings,
               FeatureSearchSettings_::Id,
               FeatureSearchSettings_::Key,
               FeatureSearchSettings_::Value,
               FeatureSearchSettings_::Mtime>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "feature_search_settings";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T featureSearchSettings;
        T& operator()() { return featureSearchSettings; }
        const T& operator()() const { return featureSearchSettings; }
      };
    };
  };
} // namespace database
} // namespace dltool
