#pragma once

// generated by 3rdparty\sqlpp11\scripts\sqlite2cpp.py D:\Project\DeepLearningTool\src\database\include\database\ddl\create_images.sql D:\Project\DeepLearningTool\src\database\include\database\ddl\ImagesTable dltool::database

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace dltool
{
namespace database
{
  namespace Images_
  {
    struct Id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct DatasetId
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "dataset_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T datasetId;
            T& operator()() { return datasetId; }
            const T& operator()() const { return datasetId; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct Path
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "path";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T path;
            T& operator()() { return path; }
            const T& operator()() const { return path; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct ExtraData
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "extra_data";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T extraData;
            T& operator()() { return extraData; }
            const T& operator()() const { return extraData; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::blob, sqlpp::tag::can_be_null>;
    };
  } // namespace Images_

  struct Images: sqlpp::table_t<Images,
               Images_::Id,
               Images_::DatasetId,
               Images_::Path,
               Images_::ExtraData>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "images";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T images;
        T& operator()() { return images; }
        const T& operator()() const { return images; }
      };
    };
  };
} // namespace database
} // namespace dltool
