#pragma once

// generated by 3rdparty\sqlpp11\scripts\sqlite2cpp.py D:\Project\DeepLearningTool\src\database\include\database\ddl\create_label_classes.sql D:\Project\DeepLearningTool\src\database\include\database\ddl\LabelClassesTable dltool::database

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace dltool
{
namespace database
{
  namespace LabelClasses_
  {
    struct Id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct Name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T name;
            T& operator()() { return name; }
            const T& operator()() const { return name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct Color
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "color";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T color;
            T& operator()() { return color; }
            const T& operator()() const { return color; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct Shortcut
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "shortcut";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T shortcut;
            T& operator()() { return shortcut; }
            const T& operator()() const { return shortcut; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct OrdinalIndex
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "ordinal_index";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T ordinalIndex;
            T& operator()() { return ordinalIndex; }
            const T& operator()() const { return ordinalIndex; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct ExtraData
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "extra_data";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T extraData;
            T& operator()() { return extraData; }
            const T& operator()() const { return extraData; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::blob, sqlpp::tag::can_be_null>;
    };
  } // namespace LabelClasses_

  struct LabelClasses: sqlpp::table_t<LabelClasses,
               LabelClasses_::Id,
               LabelClasses_::Name,
               LabelClasses_::Color,
               LabelClasses_::Shortcut,
               LabelClasses_::OrdinalIndex,
               LabelClasses_::ExtraData>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "label_classes";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T labelClasses;
        T& operator()() { return labelClasses; }
        const T& operator()() const { return labelClasses; }
      };
    };
  };
} // namespace database
} // namespace dltool
