#pragma once

// generated by 3rdparty/sqlpp11/scripts/sqlite2cpp.py src/database/include/database/ddl/create_label_display_settings.sql src/database/include/database/ddl/LabelDisplaySettingsTable dltool::database

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace dltool
{
namespace database
{
  namespace LabelDisplaySettings_
  {
    struct Id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct Key
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "key";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T key;
            T& operator()() { return key; }
            const T& operator()() const { return key; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct Value
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "value";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T value;
            T& operator()() { return value; }
            const T& operator()() const { return value; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct Mtime
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "mtime";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T mtime;
            T& operator()() { return mtime; }
            const T& operator()() const { return mtime; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
  } // namespace LabelDisplaySettings_

  struct LabelDisplaySettings: sqlpp::table_t<LabelDisplaySettings,
               LabelDisplaySettings_::Id,
               LabelDisplaySettings_::Key,
               LabelDisplaySettings_::Value,
               LabelDisplaySettings_::Mtime>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "label_display_settings";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T labelDisplaySettings;
        T& operator()() { return labelDisplaySettings; }
        const T& operator()() const { return labelDisplaySettings; }
      };
    };
  };
} // namespace database
} // namespace dltool
