#pragma once

// generated by 3rdparty\sqlpp11\scripts\sqlite2cpp.py D:\Project\DeepLearningTool\src\database\include\database\ddl\create_labels.sql D:\Project\DeepLearningTool\src\database\include\database\ddl\LabelsTable dltool::database

#include <sqlpp11/char_sequence.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/table.h>

namespace dltool { namespace database {
namespace Labels_ {
struct Id
{
    struct _alias_t
    {
        static constexpr const char _literal[] = "id";
        using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;

        template<typename T>
        struct _member_t
        {
            T id;

            T &operator()()
            {
                return id;
            }

            const T &operator()() const
            {
                return id;
            }
        };
    };

    using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
};

struct ImageId
{
    struct _alias_t
    {
        static constexpr const char _literal[] = "image_id";
        using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;

        template<typename T>
        struct _member_t
        {
            T imageId;

            T &operator()()
            {
                return imageId;
            }

            const T &operator()() const
            {
                return imageId;
            }
        };
    };

    using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
};

struct LabelClassId
{
    struct _alias_t
    {
        static constexpr const char _literal[] = "label_class_id";
        using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;

        template<typename T>
        struct _member_t
        {
            T labelClassId;

            T &operator()()
            {
                return labelClassId;
            }

            const T &operator()() const
            {
                return labelClassId;
            }
        };
    };

    using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
};

struct RegionType
{
    struct _alias_t
    {
        static constexpr const char _literal[] = "region_type";
        using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;

        template<typename T>
        struct _member_t
        {
            T regionType;

            T &operator()()
            {
                return regionType;
            }

            const T &operator()() const
            {
                return regionType;
            }
        };
    };

    using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
};

struct Region
{
    struct _alias_t
    {
        static constexpr const char _literal[] = "region";
        using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;

        template<typename T>
        struct _member_t
        {
            T region;

            T &operator()()
            {
                return region;
            }

            const T &operator()() const
            {
                return region;
            }
        };
    };

    using _traits = sqlpp::make_traits<sqlpp::blob, sqlpp::tag::can_be_null>;
};

struct OrdinalIndex
{
    struct _alias_t
    {
        static constexpr const char _literal[] = "ordinal_index";
        using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;

        template<typename T>
        struct _member_t
        {
            T ordinalIndex;

            T &operator()()
            {
                return ordinalIndex;
            }

            const T &operator()() const
            {
                return ordinalIndex;
            }
        };
    };

    using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
};

struct ExtraData
{
    struct _alias_t
    {
        static constexpr const char _literal[] = "extra_data";
        using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;

        template<typename T>
        struct _member_t
        {
            T extraData;

            T &operator()()
            {
                return extraData;
            }

            const T &operator()() const
            {
                return extraData;
            }
        };
    };

    using _traits = sqlpp::make_traits<sqlpp::blob, sqlpp::tag::can_be_null>;
};
} // namespace Labels_

struct Labels
    : sqlpp::table_t<Labels, Labels_::Id, Labels_::ImageId, Labels_::LabelClassId, Labels_::RegionType, Labels_::Region,
                     Labels_::OrdinalIndex, Labels_::ExtraData>
{
    struct _alias_t
    {
        static constexpr const char _literal[] = "labels";
        using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;

        template<typename T>
        struct _member_t
        {
            T labels;

            T &operator()()
            {
                return labels;
            }

            const T &operator()() const
            {
                return labels;
            }
        };
    };
};
}} // namespace dltool::database
