#pragma once

// generated by 3rdparty/sqlpp11/scripts/sqlite2cpp.py src/database/include/database/ddl/create_models.sql src/database/include/database/ddl/ModelsTable dltool::database

#include <sqlpp11/char_sequence.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/table.h>

namespace dltool { namespace database {
namespace Models_ {
struct Id
{
    struct _alias_t
    {
        static constexpr const char _literal[] = "id";
        using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;

        template<typename T>
        struct _member_t
        {
            T id;

            T &operator()()
            {
                return id;
            }

            const T &operator()() const
            {
                return id;
            }
        };
    };

    using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
};

struct Name
{
    struct _alias_t
    {
        static constexpr const char _literal[] = "name";
        using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;

        template<typename T>
        struct _member_t
        {
            T name;

            T &operator()()
            {
                return name;
            }

            const T &operator()() const
            {
                return name;
            }
        };
    };

    using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
};

struct Uuid
{
    struct _alias_t
    {
        static constexpr const char _literal[] = "uuid";
        using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;

        template<typename T>
        struct _member_t
        {
            T uuid;

            T &operator()()
            {
                return uuid;
            }

            const T &operator()() const
            {
                return uuid;
            }
        };
    };

    using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
};

struct FrameworkName
{
    struct _alias_t
    {
        static constexpr const char _literal[] = "framework_name";
        using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;

        template<typename T>
        struct _member_t
        {
            T frameworkName;

            T &operator()()
            {
                return frameworkName;
            }

            const T &operator()() const
            {
                return frameworkName;
            }
        };
    };

    using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
};

struct ModelArchitecture
{
    struct _alias_t
    {
        static constexpr const char _literal[] = "model_architecture";
        using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;

        template<typename T>
        struct _member_t
        {
            T modelArchitecture;

            T &operator()()
            {
                return modelArchitecture;
            }

            const T &operator()() const
            {
                return modelArchitecture;
            }
        };
    };

    using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
};

struct TrainingResult
{
    struct _alias_t
    {
        static constexpr const char _literal[] = "training_result";
        using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;

        template<typename T>
        struct _member_t
        {
            T trainingResult;

            T &operator()()
            {
                return trainingResult;
            }

            const T &operator()() const
            {
                return trainingResult;
            }
        };
    };

    using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
};

struct TestResult
{
    struct _alias_t
    {
        static constexpr const char _literal[] = "test_result";
        using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;

        template<typename T>
        struct _member_t
        {
            T testResult;

            T &operator()()
            {
                return testResult;
            }

            const T &operator()() const
            {
                return testResult;
            }
        };
    };

    using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
};

struct Ctime
{
    struct _alias_t
    {
        static constexpr const char _literal[] = "ctime";
        using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;

        template<typename T>
        struct _member_t
        {
            T ctime;

            T &operator()()
            {
                return ctime;
            }

            const T &operator()() const
            {
                return ctime;
            }
        };
    };

    using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
};

struct Mtime
{
    struct _alias_t
    {
        static constexpr const char _literal[] = "mtime";
        using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;

        template<typename T>
        struct _member_t
        {
            T mtime;

            T &operator()()
            {
                return mtime;
            }

            const T &operator()() const
            {
                return mtime;
            }
        };
    };

    using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
};

struct ExtraData
{
    struct _alias_t
    {
        static constexpr const char _literal[] = "extra_data";
        using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;

        template<typename T>
        struct _member_t
        {
            T extraData;

            T &operator()()
            {
                return extraData;
            }

            const T &operator()() const
            {
                return extraData;
            }
        };
    };

    using _traits = sqlpp::make_traits<sqlpp::blob, sqlpp::tag::can_be_null>;
};
} // namespace Models_

struct Models
    : sqlpp::table_t<Models, Models_::Id, Models_::Uuid, Models_::Name, Models_::FrameworkName,
                     Models_::ModelArchitecture, Models_::TrainingResult, Models_::TestResult, Models_::Ctime,
                     Models_::Mtime, Models_::ExtraData>
{
    struct _alias_t
    {
        static constexpr const char _literal[] = "models";
        using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;

        template<typename T>
        struct _member_t
        {
            T models;

            T &operator()()
            {
                return models;
            }

            const T &operator()() const
            {
                return models;
            }
        };
    };
};
}} // namespace dltool::database
