#pragma once

// generated by F:\Projects\DeepLearningTool\3rdparty\sqlpp11\scripts\sqlite2cpp.py F:\Projects\DeepLearningTool\src\database\include\database\ddl\create_model_datasets.sql F:\Projects\DeepLearningTool\src\database\include\database\ddl\ModelDatasetsTable dltool::database

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace dltool
{
namespace database
{
  namespace Datasets_
  {
    struct Type
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "type";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T type;
            T& operator()() { return type; }
            const T& operator()() const { return type; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct DatasetId
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "dataset_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T datasetId;
            T& operator()() { return datasetId; }
            const T& operator()() const { return datasetId; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct ClassIds
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "class_ids";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T classIds;
            T& operator()() { return classIds; }
            const T& operator()() const { return classIds; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
  } // namespace Datasets_

  struct ModelDatasets: sqlpp::table_t<ModelDatasets,
               Datasets_::Type,
               Datasets_::DatasetId,
               Datasets_::ClassIds>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "datasets";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T datasets;
        T& operator()() { return datasets; }
        const T& operator()() const { return datasets; }
      };
    };
  };
} // namespace database
} // namespace dltool
