#pragma once

// generated by F:\Projects\DeepLearningTool\3rdparty\sqlpp11\scripts\sqlite2cpp.py F:\Projects\DeepLearningTool\src\database\include\database\ddl\create_prediction.sql F:\Projects\DeepLearningTool\src\database\include\database\ddl\PredictionTable dltool::database

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace dltool
{
namespace database
{
  namespace Prediction_
  {
    struct ImageId
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "image_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T imageId;
            T& operator()() { return imageId; }
            const T& operator()() const { return imageId; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct Data
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "data";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T data;
            T& operator()() { return data; }
            const T& operator()() const { return data; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
  } // namespace Prediction_

  struct Prediction: sqlpp::table_t<Prediction,
               Prediction_::ImageId,
               Prediction_::Data>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "prediction";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T prediction;
        T& operator()() { return prediction; }
        const T& operator()() const { return prediction; }
      };
    };
  };
} // namespace database
} // namespace dltool
