#pragma once

// generated by 3rdparty\sqlpp11\scripts\sqlite2cpp.py src\database\include\database\ddl\create_settings.sql src\database\include\database\ddl\SettingsTable dltool::database

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace dltool
{
namespace database
{
  namespace Settings_
  {
    struct Id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct GroupName
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "group_name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T groupName;
            T& operator()() { return groupName; }
            const T& operator()() const { return groupName; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct SettingKey
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "setting_key";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T settingKey;
            T& operator()() { return settingKey; }
            const T& operator()() const { return settingKey; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct SettingValue
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "setting_value";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T settingValue;
            T& operator()() { return settingValue; }
            const T& operator()() const { return settingValue; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct ValueType
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "value_type";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T valueType;
            T& operator()() { return valueType; }
            const T& operator()() const { return valueType; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct Mtime
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "mtime";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T mtime;
            T& operator()() { return mtime; }
            const T& operator()() const { return mtime; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct ExtraData
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "extra_data";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T extraData;
            T& operator()() { return extraData; }
            const T& operator()() const { return extraData; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::blob, sqlpp::tag::can_be_null>;
    };
  } // namespace Settings_

  struct Settings: sqlpp::table_t<Settings,
               Settings_::Id,
               Settings_::GroupName,
               Settings_::SettingKey,
               Settings_::SettingValue,
               Settings_::ValueType,
               Settings_::Mtime,
               Settings_::ExtraData>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "settings";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T settings;
        T& operator()() { return settings; }
        const T& operator()() const { return settings; }
      };
    };
  };
} // namespace database
} // namespace dltool
