#pragma once

// generated by 3rdparty/sqlpp11/scripts/sqlite2cpp.py src/database/include/database/ddl/create_tags.sql src/database/include/database/ddl/TagsTable dltool::database

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace dltool
{
namespace database
{
  namespace Tags_
  {
    struct Id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct ImageId
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "image_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T imageId;
            T& operator()() { return imageId; }
            const T& operator()() const { return imageId; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct LabelId
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "label_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T labelId;
            T& operator()() { return labelId; }
            const T& operator()() const { return labelId; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct TagIds
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "tag_ids";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T tagIds;
            T& operator()() { return tagIds; }
            const T& operator()() const { return tagIds; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::blob, sqlpp::tag::require_insert>;
    };
    struct Type
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "type";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T type;
            T& operator()() { return type; }
            const T& operator()() const { return type; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct ExtraData
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "extra_data";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T extraData;
            T& operator()() { return extraData; }
            const T& operator()() const { return extraData; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::blob, sqlpp::tag::can_be_null>;
    };
  } // namespace Tags_

  struct Tags: sqlpp::table_t<Tags,
               Tags_::Id,
               Tags_::ImageId,
               Tags_::LabelId,
               Tags_::TagIds,
               Tags_::Type,
               Tags_::ExtraData>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "tags";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T tags;
        T& operator()() { return tags; }
        const T& operator()() const { return tags; }
      };
    };
  };
} // namespace database
} // namespace dltool
