#pragma once

// generated by F:\Projects\DeepLearningTool\3rdparty\sqlpp11\scripts\sqlite2cpp.py F:\Projects\DeepLearningTool\src\database\include\database\ddl\create_task_info.sql F:\Projects\DeepLearningTool\src\database\include\database\ddl\TaskInfoTable dltool::database

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace dltool
{
namespace database
{
  namespace TaskInfo_
  {
    struct TaskId
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "task_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T taskId;
            T& operator()() { return taskId; }
            const T& operator()() const { return taskId; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct Ctime
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "ctime";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T ctime;
            T& operator()() { return ctime; }
            const T& operator()() const { return ctime; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct Mtime
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "mtime";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T mtime;
            T& operator()() { return mtime; }
            const T& operator()() const { return mtime; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
  } // namespace TaskInfo_

  struct TaskInfo: sqlpp::table_t<TaskInfo,
               TaskInfo_::TaskId,
               TaskInfo_::Ctime,
               TaskInfo_::Mtime>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "task_info";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T taskInfo;
        T& operator()() { return taskInfo; }
        const T& operator()() const { return taskInfo; }
      };
    };
  };
} // namespace database
} // namespace dltool
