#pragma once

// generated by F:\Projects\DeepLearningTool\3rdparty\sqlpp11\scripts\sqlite2cpp.py F:\Projects\DeepLearningTool\src\database\include\database\ddl\create_test_params.sql F:\Projects\DeepLearningTool\src\database\include\database\ddl\TestParamsTable dltool::database

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace dltool
{
namespace database
{
  namespace TestParams_
  {
    struct Group
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "!group";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T group;
            T& operator()() { return group; }
            const T& operator()() const { return group; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct NameEn
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "name_en";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T nameEn;
            T& operator()() { return nameEn; }
            const T& operator()() const { return nameEn; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct Value
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "value";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T value;
            T& operator()() { return value; }
            const T& operator()() const { return value; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct Type
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "type";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T type;
            T& operator()() { return type; }
            const T& operator()() const { return type; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
  } // namespace TestParams_

  struct TestParams: sqlpp::table_t<TestParams,
               TestParams_::Group,
               TestParams_::NameEn,
               TestParams_::Value,
               TestParams_::Type>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "test_params";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T testParams;
        T& operator()() { return testParams; }
        const T& operator()() const { return testParams; }
      };
    };
  };
} // namespace database
} // namespace dltool
