#pragma once

// generated by F:\Projects\DeepLearningTool\3rdparty\sqlpp11\scripts\sqlite2cpp.py F:\Projects\DeepLearningTool\src\database\include\database\ddl\create_test_tasks.sql F:\Projects\DeepLearningTool\src\database\include\database\ddl\TestTasksTable dltool::database

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace dltool
{
namespace database
{
  namespace TestTasks_
  {
    struct TaskId
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "task_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T taskId;
            T& operator()() { return taskId; }
            const T& operator()() const { return taskId; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct Name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T name;
            T& operator()() { return name; }
            const T& operator()() const { return name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct Ctime
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "ctime";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T ctime;
            T& operator()() { return ctime; }
            const T& operator()() const { return ctime; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct Mtime
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "mtime";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T mtime;
            T& operator()() { return mtime; }
            const T& operator()() const { return mtime; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
  } // namespace TestTasks_

  struct TestTasks: sqlpp::table_t<TestTasks,
               TestTasks_::TaskId,
               TestTasks_::Name,
               TestTasks_::Ctime,
               TestTasks_::Mtime>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "test_tasks";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T testTasks;
        T& operator()() { return testTasks; }
        const T& operator()() const { return testTasks; }
      };
    };
  };
} // namespace database
} // namespace dltool
