#pragma once

// generated by 3rdparty\sqlpp11\scripts\sqlite2cpp.py src\data\include\data\ddl\create_recent_projects.sql src\data\include\data\ddl\RecentProjectsTable dltool::data

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace dltool
{
namespace data
{
  namespace RecentProjects_
  {
    struct Id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct Path
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "path";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T path;
            T& operator()() { return path; }
            const T& operator()() const { return path; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace RecentProjects_

  struct RecentProjects: sqlpp::table_t<RecentProjects,
               RecentProjects_::Id,
               RecentProjects_::Path>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "recent_projects";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T recentProjects;
        T& operator()() { return recentProjects; }
        const T& operator()() const { return recentProjects; }
      };
    };
  };
} // namespace data
} // namespace dltool
