#pragma once

// generated by 3rdparty\sqlpp11\scripts\sqlite2cpp.py D:\Project\DeepLearningTool\src\data\include\data\ddl\create_tags.sql D:\Project\DeepLearningTool\src\data\include\data\ddl\TagsTable dltool::data

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace dltool
{
namespace data
{
  namespace Tags_
  {
    struct Id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct Name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T name;
            T& operator()() { return name; }
            const T& operator()() const { return name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct ExtraData
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "extra_data";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T extraData;
            T& operator()() { return extraData; }
            const T& operator()() const { return extraData; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::blob, sqlpp::tag::can_be_null>;
    };
  } // namespace Tags_

  struct Tags: sqlpp::table_t<Tags,
               Tags_::Id,
               Tags_::Name,
               Tags_::ExtraData>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "tags";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T tags;
        T& operator()() { return tags; }
        const T& operator()() const { return tags; }
      };
    };
  };
} // namespace data
} // namespace dltool
