UISettings:
  table: ui_settings
  accessor: ui
  category: general
  ordinal_index: 30
  label: 界面设置
  sections:
    图像:
      - name_en: brightness
        name_cn: 图像亮度
        desc: 用于配置界面设置中图像相关的图像亮度。
        property_name: imageBrightness
        value: 0.0
        value_type: double
        value_range: [-1.0, 1.0, 0.1]
        control_type: slider

      - name_en: contrast
        name_cn: 图像对比度
        desc: 用于配置界面设置中图像相关的图像对比度。
        property_name: imageContrast
        value: 0.0
        value_type: double
        value_range: [-1.0, 1.0, 0.1]
        control_type: slider
