include_guard(GLOBAL)

include(CMakeParseArguments)

# Collect source files and make additions/removals trigger a CMake reconfigure.
function(dlt_glob_sources OUTPUT_VAR)
    set(options RECURSE)
    set(oneValueArgs ROOT)
    set(multiValueArgs PATTERNS)
    cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(ARG_UNPARSED_ARGUMENTS OR NOT ARG_PATTERNS)
        message(FATAL_ERROR "dlt_glob_sources requires PATTERNS")
    endif()

    if(ARG_ROOT)
        set(_root "${ARG_ROOT}")
    else()
        set(_root "${CMAKE_CURRENT_SOURCE_DIR}")
    endif()

    set(_patterns)
    foreach(_pattern IN LISTS ARG_PATTERNS)
        list(APPEND _patterns "${_root}/${_pattern}")
    endforeach()

    if(ARG_RECURSE)
        file(GLOB_RECURSE _files LIST_DIRECTORIES false CONFIGURE_DEPENDS ${_patterns})
    else()
        file(GLOB _files LIST_DIRECTORIES false CONFIGURE_DEPENDS ${_patterns})
    endif()

    list(REMOVE_DUPLICATES _files)
    list(SORT _files)
    set(${OUTPUT_VAR} "${_files}" PARENT_SCOPE)
endfunction()

# Register an arbitrary command as a CTest test and apply common properties.
function(dlt_register_test TEST_NAME)
    set(options)
    set(oneValueArgs WORKING_DIRECTORY)
    set(multiValueArgs COMMAND LABELS ENVIRONMENT_MODIFICATION FIXTURES_REQUIRED FIXTURES_SETUP)
    cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(ARG_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "Unknown dlt_register_test arguments: ${ARG_UNPARSED_ARGUMENTS}")
    endif()
    if(NOT ARG_COMMAND)
        set(ARG_COMMAND "${TEST_NAME}")
    endif()

    add_test(NAME "${TEST_NAME}" COMMAND ${ARG_COMMAND})

    if(ARG_LABELS)
        set_tests_properties("${TEST_NAME}" PROPERTIES LABELS "${ARG_LABELS}")
    endif()
    if(ARG_ENVIRONMENT_MODIFICATION)
        set_tests_properties("${TEST_NAME}" PROPERTIES
            ENVIRONMENT_MODIFICATION "${ARG_ENVIRONMENT_MODIFICATION}"
        )
    endif()
    if(ARG_FIXTURES_REQUIRED)
        set_tests_properties("${TEST_NAME}" PROPERTIES FIXTURES_REQUIRED "${ARG_FIXTURES_REQUIRED}")
    endif()
    if(ARG_FIXTURES_SETUP)
        set_tests_properties("${TEST_NAME}" PROPERTIES FIXTURES_SETUP "${ARG_FIXTURES_SETUP}")
    endif()
    if(ARG_WORKING_DIRECTORY)
        set_tests_properties("${TEST_NAME}" PROPERTIES WORKING_DIRECTORY "${ARG_WORKING_DIRECTORY}")
    endif()
endfunction()

# Create a test executable and register its default CTest entry.
function(dlt_add_test_executable TARGET_NAME)
    set(options NO_TEST QT_EXECUTABLE)
    set(oneValueArgs TEST_NAME)
    set(multiValueArgs SOURCES LINK_LIBRARIES INCLUDE_DIRECTORIES COMPILE_DEFINITIONS
                       TEST_ARGUMENTS LABELS ENVIRONMENT_MODIFICATION FIXTURES_REQUIRED FIXTURES_SETUP)
    cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(ARG_UNPARSED_ARGUMENTS OR NOT ARG_SOURCES)
        message(FATAL_ERROR "dlt_add_test_executable requires SOURCES")
    endif()

    if(ARG_QT_EXECUTABLE)
        qt_add_executable(${TARGET_NAME} ${ARG_SOURCES})
    else()
        add_executable(${TARGET_NAME} ${ARG_SOURCES})
    endif()

    if(ARG_LINK_LIBRARIES)
        target_link_libraries(${TARGET_NAME} PRIVATE ${ARG_LINK_LIBRARIES})
    endif()
    if(ARG_INCLUDE_DIRECTORIES)
        target_include_directories(${TARGET_NAME} PRIVATE ${ARG_INCLUDE_DIRECTORIES})
    endif()
    if(ARG_COMPILE_DEFINITIONS)
        target_compile_definitions(${TARGET_NAME} PRIVATE ${ARG_COMPILE_DEFINITIONS})
    endif()

    if(NOT ARG_NO_TEST)
        if(ARG_TEST_NAME)
            set(_test_name "${ARG_TEST_NAME}")
        else()
            set(_test_name "${TARGET_NAME}")
        endif()

        set(_register_arguments COMMAND "${TARGET_NAME}")
        if(ARG_TEST_ARGUMENTS)
            list(APPEND _register_arguments ${ARG_TEST_ARGUMENTS})
        endif()
        if(ARG_LABELS)
            list(APPEND _register_arguments LABELS "${ARG_LABELS}")
        endif()
        if(ARG_ENVIRONMENT_MODIFICATION)
            list(APPEND _register_arguments ENVIRONMENT_MODIFICATION "${ARG_ENVIRONMENT_MODIFICATION}")
        endif()
        if(ARG_FIXTURES_REQUIRED)
            list(APPEND _register_arguments FIXTURES_REQUIRED "${ARG_FIXTURES_REQUIRED}")
        endif()
        if(ARG_FIXTURES_SETUP)
            list(APPEND _register_arguments FIXTURES_SETUP "${ARG_FIXTURES_SETUP}")
        endif()
        dlt_register_test("${_test_name}" ${_register_arguments})
    endif()
endfunction()
