include("${CMAKE_CURRENT_LIST_DIR}/ConfigDependencyDefaults.cmake")

dlt_dependency_resolve_path(
    _dlt_qt_root _dlt_qt_origin qt
    VARIABLES Qt6_ROOT QT6_ROOT Qt_ROOT QT_ROOT QTDIR
    ENVIRONMENT_VARIABLES Qt6_ROOT QT6_ROOT Qt_ROOT QT_ROOT QTDIR
    PREFIX_PATHS ${CMAKE_PREFIX_PATH}
    REQUIRED_FILES lib/cmake/Qt6/Qt6Config.cmake
)
if(_dlt_qt_root)
    dlt_dependency_cache_set(
        Qt6_ROOT "${_dlt_qt_root}" PATH
        "Qt6 installation root directory"
        DLT_DEPENDENCY_QT6_ROOT "${_dlt_qt_origin}")
endif()

if(DEFINED Qt6_ROOT AND NOT Qt6_ROOT STREQUAL "")
    set(Qt6_CMAKE_DIR "${Qt6_ROOT}/lib/cmake")
    set(Qt6_DIR "${Qt6_CMAKE_DIR}/Qt6")
    set(Qt6QmlTools_DIR "${Qt6_CMAKE_DIR}/Qt6QmlTools")
    set(QT_QML_IMPORT_DIR "${Qt6_ROOT}/qml")
    list(PREPEND CMAKE_PREFIX_PATH "${Qt6_ROOT}")
endif()

# 寻找Qt6的组件
find_package(Qt6 REQUIRED COMPONENTS Core Gui Quick Widgets Charts Network WebEngineQuick)

# 寻找Qt6的测试组件
find_package(Qt6 REQUIRED COMPONENTS QuickTest)

if(TARGET Qt6::Core AND (NOT DEFINED QT_QML_IMPORT_DIR OR QT_QML_IMPORT_DIR STREQUAL ""))
    get_target_property(_qt6_core_location Qt6::Core LOCATION)
    if(_qt6_core_location)
        get_filename_component(_qt6_bin_dir "${_qt6_core_location}" DIRECTORY)
        if(IS_DIRECTORY "${_qt6_bin_dir}/../qml")
            get_filename_component(QT_QML_IMPORT_DIR "${_qt6_bin_dir}/../qml" ABSOLUTE)
        endif()
    endif()
endif()

# 设置Qt6项目
qt_standard_project_setup(REQUIRES 6)

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)

# 设置 QTP0001 策略为 NEW，即使使用新的资源前缀 :/qt/qml/ 作为默认值
# Qt6.8 设置 QTP0004 策略为 NEW，抑制警告 Qt policy QTP0004 is not set: 
# You need qmldir files for each extra directory that contains .qml files for your module. 
qt_policy(SET QTP0001 NEW)
if(Qt6_VERSION VERSION_GREATER_EQUAL 6.8.0)
    qt_policy(SET QTP0004 NEW)
endif()

# 添加 qml 导入目录
# QML_IMPORT_PATH 用于支持语法高亮
list(APPEND QML_IMPORT_PATH ${CMAKE_BINARY_DIR})

if(DEFINED QT_QML_IMPORT_DIR AND NOT QT_QML_IMPORT_DIR STREQUAL "")
    list(APPEND QML_IMPORT_PATH ${QT_QML_IMPORT_DIR})
endif()

# 去除重复
list(REMOVE_DUPLICATES QML_IMPORT_PATH)

# 将导入目录添加到 cache, 强制更新
set(QML_IMPORT_PATH ${QML_IMPORT_PATH}
    CACHE STRING "qml import paths"
    FORCE
)

function(generate_qml_test_list QML_TEST_DIR OUTPUT_HEADER)
    file(GLOB QML_TEST_FILES "${QML_TEST_DIR}/tst_*.qml")

    # 提取测试名称（无后缀、无路径）
    set(QML_TEST_NAMES "")
    foreach(f ${QML_TEST_FILES})
        get_filename_component(fname ${f} NAME_WE)
        list(APPEND QML_TEST_NAMES ${fname})
    endforeach()

    # 生成 qml_test_list.h
    set(HEADER_PATH "${OUTPUT_HEADER}")

    file(WRITE ${HEADER_PATH} "// Auto-generated by CMake\n")
    file(APPEND ${HEADER_PATH} "#pragma once\n\n")
    file(APPEND ${HEADER_PATH} "#include <cstddef>\n\n")
    file(APPEND ${HEADER_PATH} "static const char* g_qml_tests[] = {\n")

    # 将测试名称写入头文件, 并写入测试数量
    set(QML_TEST_NAMES_COUNT 0)
    foreach(name ${QML_TEST_NAMES})
        file(APPEND ${HEADER_PATH} "    \"${name}\",\n")
        math(EXPR QML_TEST_NAMES_COUNT "${QML_TEST_NAMES_COUNT} + 1")
    endforeach()

    file(APPEND ${HEADER_PATH} "};\n")
    file(APPEND ${HEADER_PATH} "static constexpr size_t g_qml_tests_count = ${QML_TEST_NAMES_COUNT};\n")
endfunction()
